name: Trending Service CD

on:
  push:
    branches: [ main, dev ]

  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'services/trending-service/requirements.txt'
      
      - name: Install dependencies
        working-directory: ./services/trending-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test uvicorn server launch
        working-directory: ./services/trending-service
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8001 &
          sleep 5
          curl -s http://localhost:8001/health || curl -s http://localhost:8001/ || true
          pkill -f uvicorn || true

  build-and-push:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Determine image tag
        id: determine_tag
        run: |
          # Get short commit SHA
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Extract branch name from GITHUB_REF
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          
          # Determine the tag based on branch
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "tag=dev-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "env=dev" >> $GITHUB_OUTPUT
          else
            # For any other branch, use branch name + commit SHA
            SAFE_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/\//-/g')
            echo "tag=${SAFE_BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "env=dev" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/trending-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:${{ steps.determine_tag.outputs.tag }}
          build-args: |
            SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }}
            DATA_PATH=/app/data
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PORT=${{ secrets.DB_PORT }}
            DATABASE=${{ secrets.DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DIALECT=${{ secrets.DB_DIALECT }}
            DO_DB_NAME=${{ secrets.DO_DB_NAME }}
            DO_DB_PORT=${{ secrets.DO_DB_PORT }}
            DO_DB_HOST=${{ secrets.DO_DB_HOST }}
            DO_DB_USERNAME=${{ secrets.DO_DB_USERNAME }}
            DO_DB_PASSWORD=${{ secrets.DO_DB_PASSWORD }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_USER=${{ secrets.REDIS_USER }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_CHANNEL=${{ secrets.REDIS_CHANNEL }}

  update-infrastructure:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for SHA
        uses: actions/checkout@v3
        
      - name: Set service name and tag
        id: service_info
        run: |
          echo "SERVICE=trending-service" >> $GITHUB_ENV
          
          # Extract branch name from GITHUB_REF
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          
          # Get short commit SHA
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Determine the env and tag based on branch
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TAG=dev-${SHORT_SHA}" >> $GITHUB_ENV
          else
            # For feature branches
            echo "ENV=dev" >> $GITHUB_ENV
            # Extract the branch name, replace / with -
            SAFE_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/\//-/g')
            echo "TAG=${SAFE_BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_ENV
          fi
          
          echo "SOURCE_BRANCH=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Checkout infrastructure branch
        uses: actions/checkout@v3
        with:
          ref: infrastructure
          token: ${{ secrets.ARGOCD_GITHUB_TOKEN }}  # Use a token with write permissions
      
      - name: Configure Git
        run: |
          git config user.name "ArgoCD Bot"
          git config user.email "argocd-bot@example.com"
      
      - name: Update image tag in Helm values
        run: |
          echo "Updating $SERVICE in charts/$ENV/values.yaml to tag: $TAG"
          
          # Check if values.yaml exists
          if [[ ! -f "charts/$ENV/values.yaml" ]]; then
            echo "Error: charts/$ENV/values.yaml does not exist!"
            exit 1
          fi
          
          # Update the tag in values.yaml for the specific service
          yq -i '.services."trending-service".tag = env(TAG)' "charts/$ENV/values.yaml" || \
          sed -i "s/\(trending-service:.*\n.*containerName:.*\n.*image:.*\n.*tag:\).*/\1 $TAG/" "charts/$ENV/values.yaml"
          
          # Show the diff for debugging
          git diff
      
      - name: Commit and push if there are changes
        run: |
          # Check if there are changes to commit
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add charts/$ENV/values.yaml
          git commit -m "Update $SERVICE image tag to $TAG (from branch $SOURCE_BRANCH) [skip ci]"
          git push